version: "3.8"

services:
  mongo1:
    image: "mongo:4.4.5-bionic"
    ports: 
      - "37017:27017"
    command: mongod
  mongo2:
    image: "mongo:4.4.5-bionic"
    ports: 
      - "47017:27017"
    command: mongod
  redis:
    image: "redis:6.2.1"
    ports:
      - "6379:6379"
    command: redis-server
  series:
    depends_on:
      - mongo1
      - redis
    image: "rendra1795/entertainme-server-series"
    command: npm run dev
    ports:
      - "4002:4002"
  movies:
    depends_on:
      - mongo2
      - redis
    image: "rendra1795/entertainme-server-movies"
    command: npm run dev
    ports:
      - "4001:4001"
  orchestrator:
    depends_on:
      - redis
    image: "rendra1795/entertainme-server-orchestrator"
    command: npm run dev
    ports:
      - "4000:4000"